package org.tohu.examples.osdc;

import java.util.Calendar;
import org.tohu.Group;
import org.tohu.InvalidAnswer;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Question;
import org.tohu.Questionnaire;
import org.tohu.Note;


rule "How to get it - Question"
dialect "mvel" 
then
	Question q = new Question();
	q.setId("get-it");
	q.setAnswerType("boolean");
	q.setPresentationStyles({"checkbox"});
	q.setPreLabel("How do I get hold of this stuff?");	
	insertLogical(q);
end

rule "Get it - Note"
dialect "mvel"
when
	Question (id == "get-it", booleanAnswer == true)
then
	Note note = new Note();
	note.setId("get-it-note");
	note.setLabel("How to get it ... <a href=\"http://www.jboss.org/tohu\">Tohu JBoss Site</a>");
	note.setPresentationStyles({"expandedTip"});
	insertLogical(note);	
end	

rule "Whats happening now? - Question"
then
	Question q = new Question();
	q.setId("whats-new");
	q.setAnswerType("boolean");
	q.setPresentationStyles(new String []{"checkbox"});
	q.setPreLabel("What\'s happening now?");	
	insertLogical(q);
end

rule "Whats New - Note"
when
	Question (id == "whats-new", booleanAnswer == true)
then
	Note note = new Note();
	note.setId("whats-new-note");
	note.setLabel("Stuff about whats new");
	note.setPresentationStyles(new String []{"expandedTip"});
	insertLogical(note);	
end	